from threshold import *


def main():
    threshold = Threshold(scheme=HYBRID, N=2, gadget_type='exrec', group=False, opt_anc=False, fixed_wait=False)

    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=0, init_params=[3, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=0, init_params=[3, -0.3, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=0, init_params=[3, 0, 40])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=0, init_params=[3, -0.3, 40])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=0, init_params=[2.5, 0, 45])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=0, init_params=[2.5, -0.3, 45])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=0, init_params=[2, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=0, init_params=[2, -0.3, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.2e-3, gamma_phi=0, init_params=[2, 0, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.2e-3, gamma_phi=0, init_params=[2, -0.3, 35])

    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=1e-4, init_params=[3, 0, 40])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=1e-4, init_params=[3, -0.3, 40])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=1e-4, init_params=[3, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=1e-4, init_params=[3, -0.3, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=1e-4, init_params=[3, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=1e-4, init_params=[3, -0.3, 30])

    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=10 ** (-3.8), init_params=[3, 0, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=10 ** (-3.8), init_params=[3, -0.3, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-4, gamma_phi=10 ** (-3.8), init_params=[3, 0, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-4, gamma_phi=10 ** (-3.8), init_params=[3, -0.3, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-3.8), init_params=[3, 0, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-3.8), init_params=[3, -0.3, 35])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.8), init_params=[3, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.8), init_params=[3, -0.3, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.8), init_params=[3, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.8), init_params=[3, -0.3, 30])

    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.6), init_params=[2.5, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.6), init_params=[2.5, -0.3, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.6), init_params=[2.5, 0, 30])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.6), init_params=[2.5, -0.3, 30])

    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.4), init_params=[2.5, 0, 25])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.4), init_params=[2.5, -0.3, 25])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.4), init_params=[2.5, 0, 25])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.4), init_params=[2.5, -0.3, 25])

    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.2), init_params=[2.5, 0, 25])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.2), init_params=[2.5, -0.3, 25])

    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3), init_params=[2.9, 0, 20])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3), init_params=[2.9, -0.3, 20])

    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-2.8), init_params=[3, 0, 15])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-2.8), init_params=[3, -0.3, 15])

    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, -0.3, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=4.5e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=4.5e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, -0.3, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=5e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=5e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, -0.3, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, -0.3, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-2.6), init_params=[3.5, -0.3, 14])

    threshold = Threshold(scheme=HYBRID, N=3, gadget_type='exrec', group=False, opt_anc=False, fixed_wait=False)

    threshold.optimize_fixed_noise_with_init_params(gamma=1e-4, gamma_phi=0, init_params=[6, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=1e-4, gamma_phi=0, init_params=[6, -0.1, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=0, init_params=[5.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=0, init_params=[5.5, -0.1, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=0, init_params=[5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=0, init_params=[5, -0.1, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=0, init_params=[4.5, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=0, init_params=[4.5, -0.1, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=0, init_params=[4, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=0, init_params=[4, -0.1, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.2e-3, gamma_phi=0, init_params=[3, 0, 14])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.2e-3, gamma_phi=0, init_params=[3, -0.1, 14])

    threshold.optimize_fixed_noise_with_init_params(gamma=2.7e-3, gamma_phi=1e-4, init_params=[3, 0, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.7e-3, gamma_phi=1e-4, init_params=[3, -0.2, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=1e-4, init_params=[3, 0, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=1e-4, init_params=[3, -0.2, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.9e-3, gamma_phi=1e-4, init_params=[3, 0, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.9e-3, gamma_phi=1e-4, init_params=[3, -0.2, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-3, gamma_phi=1e-4, init_params=[3, 0, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-3, gamma_phi=1e-4, init_params=[3, -0.2, 12])

    threshold.optimize_fixed_noise_with_init_params(gamma=2.6e-3, gamma_phi=10**(-3.8), init_params=[3.5, 0, 10])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.6e-3, gamma_phi=10**(-3.8), init_params=[3.5, -0.2, 10])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.7e-3, gamma_phi=10 ** (-3.8), init_params=[3.5, 0, 11])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.7e-3, gamma_phi=10 ** (-3.8), init_params=[3.5, -0.2, 11])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=10 ** (-3.8), init_params=[3.5, 0, 12])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=10 ** (-3.8), init_params=[3.5, -0.2, 12])

    threshold.optimize_fixed_noise_with_init_params(gamma=1.8e-3, gamma_phi=10 ** (-3.4), init_params=[3.9, 0, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.8e-3, gamma_phi=10 ** (-3.4), init_params=[3.9, -0.2, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.9e-3, gamma_phi=10 ** (-3.4), init_params=[3.8, 0, 9.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.9e-3, gamma_phi=10 ** (-3.4), init_params=[3.8, -0.2, 9.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-3, gamma_phi=10 ** (-3.4), init_params=[3.7, 0, 10])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-3, gamma_phi=10 ** (-3.4), init_params=[3.7, -0.2, 10])

    threshold.optimize_fixed_noise_with_init_params(gamma=1.3e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, 0, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.3e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, -0.1, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.4e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, 0, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.4e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, -0.1, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.5e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, 0, 7.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.5e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, -0.1, 7.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, 0, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=10 ** (-3.2), init_params=[4.5, -0.1, 8])

    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-3), init_params=[6, 0, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-3), init_params=[6, -0.1, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=5e-4, gamma_phi=10 ** (-3), init_params=[6, 0, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=5e-4, gamma_phi=10 ** (-3), init_params=[6, -0.1, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3), init_params=[6, 0, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3), init_params=[6, -0.1, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3), init_params=[6, 0, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3), init_params=[6, -0.1, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=10 ** (-3), init_params=[6, 0, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=10 ** (-3), init_params=[6, -0.1, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=9e-4, gamma_phi=10 ** (-3), init_params=[6, 0, 6.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=9e-4, gamma_phi=10 ** (-3), init_params=[6, -0.1, 6.5])

    threshold.optimize_fixed_noise_with_init_params(gamma=7e-5, gamma_phi=10 ** (-2.8), init_params=[8, 0, 2.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-5, gamma_phi=10 ** (-2.8), init_params=[8, -0.1, 2.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-2.8), init_params=[6, 0, 4])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=10 ** (-2.8), init_params=[6, -0.1, 4])

    threshold = Threshold(scheme=HYBRID, N=4, gadget_type='exrec', group=False, opt_anc=False, fixed_wait=False)

    threshold.optimize_fixed_noise_with_init_params(gamma=1e-4, gamma_phi=0, init_params=[8, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=1e-4, gamma_phi=0, init_params=[8, -0.15, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=0, init_params=[8, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-4, gamma_phi=0, init_params=[8, -0.15, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=0, init_params=[8, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-4, gamma_phi=0, init_params=[8, -0.1, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=0, init_params=[7, -0.05, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=8e-4, gamma_phi=0, init_params=[7, -0.1, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=0, init_params=[6, -0.05, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=0, init_params=[6, -0.1, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.2e-3, gamma_phi=0, init_params=[5, -0.05, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.2e-3, gamma_phi=0, init_params=[5, -0.1, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-3, gamma_phi=0, init_params=[4.5, -0.05, 10])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-3, gamma_phi=0, init_params=[4.5, -0.1, 10])
    threshold.optimize_fixed_noise_with_init_params(gamma=4.8e-3, gamma_phi=0, init_params=[4, -0.05, 11])
    threshold.optimize_fixed_noise_with_init_params(gamma=4.8e-3, gamma_phi=0, init_params=[4, -0.1, 11])

    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=1e-4, init_params=[5.5, -0.05, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=1e-4, init_params=[5.5, -0.1, 6])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.8e-3, gamma_phi=1e-4, init_params=[4.5, -0.05, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.8e-3, gamma_phi=1e-4, init_params=[4.5, -0.1, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.9e-3, gamma_phi=1e-4, init_params=[4.5, -0.05, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.9e-3, gamma_phi=1e-4, init_params=[4.5, -0.1, 9])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-3, gamma_phi=1e-4, init_params=[4.5, -0.05, 9.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=4e-3, gamma_phi=1e-4, init_params=[4.5, -0.1, 9.5])

    threshold.optimize_fixed_noise_with_init_params(gamma=3e-3, gamma_phi=10**(-3.8), init_params=[4.5, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-3, gamma_phi=10**(-3.8), init_params=[4.5, -0.1, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.1e-3, gamma_phi=10 ** (-3.8), init_params=[4.5, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.1e-3, gamma_phi=10 ** (-3.8), init_params=[4.5, -0.1, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.6e-3, gamma_phi=10 ** (-3.8), init_params=[4.5, -0.05, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.6e-3, gamma_phi=10 ** (-3.8), init_params=[4.5, -0.1, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.7e-3, gamma_phi=10 ** (-3.8), init_params=[4.5, -0.05, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3.7e-3, gamma_phi=10 ** (-3.8), init_params=[4.5, -0.1, 8.5])

    threshold.optimize_fixed_noise_with_init_params(gamma=2.3e-3, gamma_phi=10 ** (-3.6), init_params=[5.1, -0.05, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.3e-3, gamma_phi=10 ** (-3.6), init_params=[5.1, -0.1, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.4e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.05, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.4e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.1, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.5e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.05, 7.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.5e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.1, 7.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.6e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.05, 7.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.6e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.1, 7.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.7e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.7e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.1, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.05, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.8e-3, gamma_phi=10 ** (-3.6), init_params=[5, -0.1, 8])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.9e-3, gamma_phi=10 ** (-3.6), init_params=[4.6, -0.05, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=2.9e-3, gamma_phi=10 ** (-3.6), init_params=[4.6, -0.1, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-3, gamma_phi=10 ** (-3.6), init_params=[4.6, -0.05, 8.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=3e-3, gamma_phi=10 ** (-3.6), init_params=[4.6, -0.1, 8.5])

    threshold.optimize_fixed_noise_with_init_params(gamma=1.5e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.05, 6.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.5e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.1, 6.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.05, 6.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.6e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.1, 6.5])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.7e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.05, 6.8])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.7e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.1, 6.8])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.8e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.05, 6.8])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.8e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.1, 6.8])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.9e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.05, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=1.9e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.1, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.05, 7])
    threshold.optimize_fixed_noise_with_init_params(gamma=2e-3, gamma_phi=10 ** (-3.4), init_params=[6, -0.1, 7])

    threshold.optimize_fixed_noise_with_init_params(gamma=5e-4, gamma_phi=10 ** (-3.2), init_params=[8, -0.05, 4])
    threshold.optimize_fixed_noise_with_init_params(gamma=5e-4, gamma_phi=10 ** (-3.2), init_params=[8, -0.1, 4])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.2), init_params=[8, -0.05, 4.2])
    threshold.optimize_fixed_noise_with_init_params(gamma=6e-4, gamma_phi=10 ** (-3.2), init_params=[8, -0.1, 4.2])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.2), init_params=[8, -0.05, 4.4])
    threshold.optimize_fixed_noise_with_init_params(gamma=7e-4, gamma_phi=10 ** (-3.2), init_params=[8, -0.1, 4.4])


if __name__ == "__main__":
    main()
